---

- src: https://github.com/luismiguelsaez/ansible-role-elk-elasticsearch.git
  scm: git
  version: master

- src: https://github.com/luismiguelsaez/ansible-role-elk-kibana.git
  scm: git
  version: master

- src: https://github.com/luismiguelsaez/ansible-role-elk-agent.git
  scm: git
  version: master

- src: https://github.com/h4rdL1nk/ansible-role-logstash.git
  scm: git
  version: pipelines-from-fileglob

- src: https://github.com/h4rdL1nk/ansible-role-filebeat.git
  scm: git
  version: master

- src: https://github.com/h4rdL1nk/ansible-role-metricbeat.git
  scm: git
  version: master

- src: https://github.com/h4rdL1nk/ansible-role-heartbeat.git
  scm: git
  version: master
