---

- name: ELK elasticsearch setup
  gather_facts: True
  hosts: elasticsearch
  become: True

  roles:

    - role: ansible-role-elk-elasticsearch
      elasticsearch_cluster_name: clustermicro
      elasticsearch_cluster_hostnames: "{% set hostnames = [] %}{% for host in groups[elasticsearch_group] %}{{ hostnames.append(hostvars[ host ]['ansible_hostname']) }}{% endfor %}{{ hostnames | unique }}"
      elasticsearch_cluster_network_addresses: "{% set addresses = [] %}{% for host in groups[elasticsearch_group] %}{{ addresses.append(hostvars[ host ]['private_ip_address']) }}{% endfor %}{{ addresses | unique }}"
      elasticsearch_security_enabled: True
