---

- name: ELK elasticsearch setup
  gather_facts: True
  hosts: elasticsearch
  become: True

  roles:

    - role: ansible-role-elk-elasticsearch
      elasticsearch_discovery_seed_hosts: "{% set addresses = [] %}{% for host in groups[elasticsearch_group] %}{{ addresses.append(hostvars[ host ]['private_ip_address']) }}{% endfor %}{{ addresses | unique }}"
      elasticsearch_cluster_name: clustermicro
      elasticsearch_cluster_initial_master_nodes: "{% set hostnames = [] %}{% for host in groups[elasticsearch_group] %}{% if 'master' in elasticsearch_node_roles %}{{ hostnames.append(hostvars[ host ]['ansible_hostname']) }}{% endif %}{% endfor %}{{ hostnames | unique }}"
      elasticsearch_security_enabled: False
      elasticsearch_certificate_local_dir: "{{ lookup('env', 'PWD') }}/files/elasticsearch/certificates/"
